### ISSUE TITLE
Cannot build on Ubuntu using build instructions

### ISSUE THREAD

**Issue by 3ach** [SynBioDex/libSBOL#106]
I get the following error when building configuration files using the linux build instructions.

I tried pulling the submodules using the command given (`git submodule update --init --recursive`) and cleared the build info and I'm still getting the same error.

JsonCpp Version: 1.8.0
Looking for C++ include clocale
Looking for C++ include clocale - found
Looking for localeconv
Looking for localeconv - found
Looking for C++ include sys/types.h
Looking for C++ include sys/types.h - found
Looking for C++ include stdint.h
Looking for C++ include stdint.h - found
Looking for C++ include stddef.h
Looking for C++ include stddef.h - found
Check size of lconv
Check size of lconv - done
Performing Test HAVE_DECIMAL_POINT
Performing Test HAVE_DECIMAL_POINT - Success
Found PythonInterp: /usr/bin/python2 (found suitable version "2.7.12", minimum required is "2.6") 
Could NOT find JsonCpp (missing:  JsonCpp_LIBRARIES JsonCpp_INCLUDE_DIRS) 
Found raptor2 library at 
Copying /usr/include/raptor2/raptor.h;/usr/include/raptor2/raptor2.h to /home/zach/libSBOL/release/library/sbol

Configuring for x64
COMPILE_DEFINITIONS = LIBXML_STATIC;RAPTOR_STATIC;LIBXSLT_STATIC;CURL_STATIC;CURL_STATICLIB
FOUND PYTHON = TRUE at /usr/lib/x86_64-linux-gnu/libpython2.7.so
PYTHON INCLUDE DIRS = /usr/include/python2.7
FOUND PYTHON VERSION 2.7.12+
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
JsonCpp_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /home/zach/libSBOL/source
   used as include directory in directory /home/zach/libSBOL/source
   used as include directory in directory /home/zach/libSBOL/source
   used as include directory in directory /home/zach/libSBOL/source
   used as include directory in directory /home/zach/libSBOL/source
   used as include directory in directory /home/zach/libSBOL/source
   used as include directory in directory /home/zach/libSBOL/source
JsonCpp_LIBRARY (ADVANCED)
    linked by target "sbol64" in directory /home/zach/libSBOL/source

Configuring incomplete, errors occurred!
See also "/home/zach/libSBOL/build/CMakeFiles/CMakeOutput.log".

**Comment by bbartley** [comment]
On Linux it's necessary to build jsoncpp from source.  I think from the CMake command line it's necessary to specify a flag -DSBOL_BUILD_JSON=TRUE

I don't have direct experience building on Linux so if this doesn't help @kirichoi can better advise

**Comment by kirichoi** [comment]
Another and preferred solution is to install using apt-get. Try 
sudo apt-get install libjsoncpp-dev
I am planning to update the documents with up-to-date build instructions.

**Comment by 3ach** [comment]
I tried using the CMake flag. I will try Kiri's solution in a little bit and respond.

**Comment by 3ach** [comment]
Installing libjsoncpp-dev fixeds it. Please update the docs.

**Comment by kirichoi** [comment]
Commit f6d348b713660562f7900e38c33aa8ddb73944ad updates the doc
