### ISSUE TITLE
Create a separate validate() function for validating Document

### ISSUE THREAD

**Issue by kirichoi** [SynBioDex/libSBOL#110]
libSBOL validates the document when writing, but it would be generally more useful if there are a separate validate() function that users can execute to check the validity of document object prior to writing.
Fix would be as simple as moving lines 917-926 in https://github.com/SynBioDex/libSBOL/blob/develop/source/document.cpp
to create a new function and Document.write() using it.
I see there's already a function called validate() for checking validation rules when objects are appended, but I think it's better to change this to something like validateObjects() and create a new function called validate() since current function is not supposed to be exposed anyway and the name is too confusing.

**Comment by cjmyers** [comment]
I agree.  Also, you might not want to validate always on write, since you might want to be able to still write even if not valid.  

Is this validate function using the validator web API?

**Comment by kirichoi** [comment]
I believe the validate function is using the web API. Also, I don't think the write function stops you from writing an invalid file. It will simply tell you the file is not valid.

**Comment by kirichoi** [comment]
Commit 25425b14615df27a8732cc2baff37768faa97bfd fixes the issue. Tested on Windows for both C++ and Python.
After creating a Document object, users can run Document.validate() to check whether the resulting rdf/xml is valid. 

Three changes:
1. New function called generate() is created. It creates rdf/xml from objects in a Document given pointers to various raptor object (that has been initialized). It is designed to reference the rdf/xml from various functions.
2. Document.write() now uses Document.validate().
3. Document.validate() function call under Document.read() is removed. Document.validate() used to exist as different function, which was pretty much useless. Might want to reintroduce in the future in a way that's compatible with new definition of Document.validate()

@bbartley : Please test out on Mac OSX
