### ISSUE TITLE
Absence of function, struct, and interface description

### ISSUE THREAD

**Issue by tramyn** [SynBioDex/libSBOL#118]
I am having a hard time looking at all the supported functions for each SBOL class found here http://synbiodex.github.io/libSBOL/annotated.html.

I noticed not many of the SBOL class have the basic functions that should be described for documentation. For example, if you look at the Sequence class, I wasn't able to find any description for its constructor (http://synbiodex.github.io/libSBOL/classsbol_1_1_sequence.html). 

The same can be said for ModuleDefinition (http://synbiodex.github.io/libSBOL/classsbol_1_1_module_definition.html)

**Comment by bbartley** [comment]
Fixed in 3a83e5510c838dd523a7ce1a663f7f7fb0d44b8b
