### ISSUE TITLE
CMake on Mac

### ISSUE THREAD

**Issue by tramyn** [SynBioDex/libSBOL#119]
Installation instruction mentioned the following, "One important difference about CMake on Mac versus Windows is that there is no GUI application....". 

However, there is a UI interface for CMake on Mac found here: https://cmake.org/download/

**Comment by kirichoi** [comment]
Does the mac also support something like cmake-gui terminal just like in linux? If that's the case, no need to download anything additionally.  Will update the doc.

**Comment by tramyn** [comment]
Are you referring to the cmake-gui terminal as running cmake commands on the mac terminal ? If so, your instructions that specify running this command "ccmake ." on the terminal works on my mac. The following set of instructions on how to compile it from the terminal through cmake is clear and can be followed through your installation instruction. So long answer short, yes, mac support cmake-gui terminal.
