### ISSUE TITLE
Update libSBOL/example directory code 

### ISSUE THREAD

**Issue by tramyn** [SynBioDex/libSBOL#121]
Some of the code provided in libSBOL/example directory does not compile correctly because method names has been altered (i.e. sequence.add() is now sequences.add() ). The examples that are provided in the directory should be updated to reflect these changes.

This same change should also be changed in the libSBOL tutorial documentations.

**Comment by kirichoi** [comment]
I think `CRISPRRepressionExample.cpp` was outdated and I pushed updated code that I was using to write tutorial on overleaf. It seems to work fine in Ubuntu at least.

**Comment by cjmyers** [comment]
Done
