### ISSUE TITLE
Extra escape characters being added to strings

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/libSBOL#123]
When strings include "'s, slashes, etc., escape characters are being added when written out and should not be needed.

**Comment by bbartley** [comment]
Raptor library parses literal strings in n-triples encoding of unicode. See https://www.w3.org/TR/2004/REC-rdf-testcases-20040210/#ntrip_strings.  This raises the question, what is the proper encoding for standard RDF/XML?

A limited solution based on regular expressions to convert ntriples encoding down to ascii is implemented in bed25631587addabb2e0310e2ee3f2864b2c7086.  Test files now pass, but this may not be a comprehensive solution.

**Comment by cjmyers** [comment]
I’ve checked with an RDF validator and both with and without escape characters are valid.  My feeling is whatever is read should be preserved on write.  The strings should not be modified during a read/write process.  So, if escapes are present, they should be kept, if not, they should not be added.
