### ISSUE TITLE
Installing on BioLinux

### ISSUE THREAD

**Issue by kirichoi** [SynBioDex/libSBOL#151]
Originally on https://github.com/SynBioDex/pySBOL/issues/47 by @alihum

Begin original issue:

> Hi,
> 
> I am trying to install pySBOL2 on BioLinux and I am using the instructions here: https://synbiodex.github.io/libSBOL/installation.html#build_from_source
> 
> I have installed all the dependencies and cloned the git
> 
> I have generated the cmake file and when I used make install I get the following error:
> 
> `ali@ali-biolinux[ali] cd pySBOL                                       [10:35AM]
> ali@ali-biolinux[pySBOL] make install                                 [10:35AM]
> [ 14%] Building CXX object source/CMakeFiles/sbol64.dir/document.cpp.o
> /home/ali/libSBOL/source/document.cpp: In function ‘std::string sbol::convert_ntriples_encoding_to_ascii(std::string)’:
> /home/ali/libSBOL/source/document.cpp:393:47: error: no matching function for call to ‘regex_replace(std::string&, std::regex, const char [2])’
>      s = regex_replace(s, regex("\\\\\""), "\"");
>                                                ^
> /home/ali/libSBOL/source/document.cpp:393:47: note: candidates are:
> In file included from /usr/include/c++/4.8/regex:62:0,
>                  from /home/ali/libSBOL/source/properties.h:38,
>                  from /home/ali/libSBOL/source/object.h:30,
>                  from /home/ali/libSBOL/source/identified.h:29,
>                  from /home/ali/libSBOL/source/toplevel.h:29,
>                  from /home/ali/libSBOL/source/componentdefinition.h:29,
>                  from /home/ali/libSBOL/source/document.h:30,
>                  from /home/ali/libSBOL/source/document.cpp:27:
> /usr/include/c++/4.8/bits/regex.h:2162:5: note: template<class _Out_iter, class _Bi_iter, class _Rx_traits, class _Ch_type> _Out_iter std::regex_replace(_Out_iter, _Bi_iter, _Bi_iter, const std::basic_regex<_Ch_type, _Rx_traits>&, const std::basic_string<_Ch_type>&, std::regex_constants::match_flag_type)
>      regex_replace(_Out_iter __out, _Bi_iter __first, _Bi_iter __last,
>      ^
> /usr/include/c++/4.8/bits/regex.h:2162:5: note:   template argument deduction/substitution failed:
> /home/ali/libSBOL/source/document.cpp:393:47: note:   deduced conflicting types for parameter ‘_Bi_iter’ (‘std::basic_regex<char>’ and ‘const char*’)
>      s = regex_replace(s, regex("\\\\\""), "\"");
>                                                ^
> In file included from /usr/include/c++/4.8/regex:62:0,
>                  from /home/ali/libSBOL/source/properties.h:38,
>                  from /home/ali/libSBOL/source/object.h:30,
>                  from /home/ali/libSBOL/source/identified.h:29,
>                  from /home/ali/libSBOL/source/toplevel.h:29,
>                  from /home/ali/libSBOL/source/componentdefinition.h:29,
>                  from /home/ali/libSBOL/source/document.h:30,
>                  from /home/ali/libSBOL/source/document.cpp:27:
> /usr/include/c++/4.8/bits/regex.h:2182:5: note: template<class _Rx_traits, class _Ch_type> std::basic_string<_Ch_type> std::regex_replace(const std::basic_string<_Ch_type>&, const std::basic_regex<_Ch_type, _Rx_traits>&, const std::basic_string<_Ch_type>&, std::regex_constants::match_flag_type)
>      regex_replace(const basic_string<_Ch_type>& __s,
>      ^
> /usr/include/c++/4.8/bits/regex.h:2182:5: note:   template argument deduction/substitution failed:
> /home/ali/libSBOL/source/document.cpp:393:47: note:   mismatched types ‘const std::basic_string<_Ch_type>’ and ‘const char [2]’
>      s = regex_replace(s, regex("\\\\\""), "\"");
>                                                ^
> /home/ali/libSBOL/source/document.cpp:394:49: error: no matching function for call to ‘regex_replace(std::string&, std::regex, const char [2])’
>      s = regex_replace(s, regex("\\\\\\\\"), "\\");
>                                                  ^
> /home/ali/libSBOL/source/document.cpp:394:49: note: candidates are:
> In file included from /usr/include/c++/4.8/regex:62:0,
>                  from /home/ali/libSBOL/source/properties.h:38,
>                  from /home/ali/libSBOL/source/object.h:30,
>                  from /home/ali/libSBOL/source/identified.h:29,
>                  from /home/ali/libSBOL/source/toplevel.h:29,
>                  from /home/ali/libSBOL/source/componentdefinition.h:29,
>                  from /home/ali/libSBOL/source/document.h:30,
>                  from /home/ali/libSBOL/source/document.cpp:27:
> /usr/include/c++/4.8/bits/regex.h:2162:5: note: template<class _Out_iter, class _Bi_iter, class _Rx_traits, class _Ch_type> _Out_iter std::regex_replace(_Out_iter, _Bi_iter, _Bi_iter, const std::basic_regex<_Ch_type, _Rx_traits>&, const std::basic_string<_Ch_type>&, std::regex_constants::match_flag_type)
>      regex_replace(_Out_iter __out, _Bi_iter __first, _Bi_iter __last,
>      ^
> /usr/include/c++/4.8/bits/regex.h:2162:5: note:   template argument deduction/substitution failed:
> /home/ali/libSBOL/source/document.cpp:394:49: note:   deduced conflicting types for parameter ‘_Bi_iter’ (‘std::basic_regex<char>’ and ‘const char*’)
>      s = regex_replace(s, regex("\\\\\\\\"), "\\");
>                                                  ^
> In file included from /usr/include/c++/4.8/regex:62:0,
>                  from /home/ali/libSBOL/source/properties.h:38,
>                  from /home/ali/libSBOL/source/object.h:30,
>                  from /home/ali/libSBOL/source/identified.h:29,
>                  from /home/ali/libSBOL/source/toplevel.h:29,
>                  from /home/ali/libSBOL/source/componentdefinition.h:29,
>                  from /home/ali/libSBOL/source/document.h:30,
>                  from /home/ali/libSBOL/source/document.cpp:27:
> /usr/include/c++/4.8/bits/regex.h:2182:5: note: template<class _Rx_traits, class _Ch_type> std::basic_string<_Ch_type> std::regex_replace(const std::basic_string<_Ch_type>&, const std::basic_regex<_Ch_type, _Rx_traits>&, const std::basic_string<_Ch_type>&, std::regex_constants::match_flag_type)
>      regex_replace(const basic_string<_Ch_type>& __s,
>      ^
> /usr/include/c++/4.8/bits/regex.h:2182:5: note:   template argument deduction/substitution failed:
> /home/ali/libSBOL/source/document.cpp:394:49: note:   mismatched types ‘const std::basic_string<_Ch_type>’ and ‘const char [2]’
>      s = regex_replace(s, regex("\\\\\\\\"), "\\");
>                                                  ^
> make[2]: *** [source/CMakeFiles/sbol64.dir/document.cpp.o] Error 1
> make[1]: *** [source/CMakeFiles/sbol64.dir/all] Error 2
> make: *** [all] Error 2
> ali@ali-biolinux[pySBOL]        `
> 
> I was wondering if you could help me out at all.
> 
> Thanks,
> 
> Ali

**Comment by kirichoi** [comment]
I believe the issue is coming from using something prior to gcc-4.9 (gcc-4.8 in your case).
I am not that familiar with biolinux but it seems like it's based on Ubuntu 14.04 so I presume following steps from this page might work?
https://askubuntu.com/questions/466651/how-do-i-use-the-latest-gcc-on-ubuntu

**Comment by bbartley** [comment]
Yes, that would be the problem.  gcc-4.8 does not have good regular expression support.  LibSBOL should compile with 4.9 or higher.
