### ISSUE TITLE
Build path for Python wrappers on Windows is not correct

### ISSUE THREAD

**Issue by bbartley** [SynBioDex/libSBOL#152]
Use  ${CMAKE_SWIG_OUTDIR} rather than ${CMAKE_INSTALL_DIR} as the path prefix for building the wrappers.  (Otherwise, it attempts to build in C:\Program Files (x86) and this requires administrator privileges).  See ./wrapper/CMakeLists.txt line 529.

**Comment by kirichoi** [comment]
It is generally recommended to change ${CMAKE_INSTALL_DIR} from it's default path especially for Windows. I would suggest to change the build instruction to make this clear instead if that has not been done yet.

**Comment by kirichoi** [comment]
Commit 817f3af546f32723270730477ad8f5de5bf0d444 adds instruction to change the default path in Windows. To be honest, building anything in Program Files is problematic and I have no idea why Cmake defaults to that directory.
