### ISSUE TITLE
libSBOL fails to build on VS

### ISSUE THREAD

**Issue by kirichoi** [SynBioDex/libSBOL#156]
When building on VS2015, two errors are returned.:

1. In file assembly.cpp line 661-664: Function build() is empty

2. In file validation.cpp line 95: 
`string& date_time = (string&)*arg;` is an illegal indirection.

**Comment by bbartley** [comment]
These are resolved as of https://github.com/SynBioDex/libSBOL/commit/a579ba9251929a38ff222abf37ac1530af3271ee
I just pushed these changes online.  Python wrappers should build fine.
However, if you try to compile ONLY libSBOL then you will get a compiler complaint about missing "Python.h".  See https://github.com/SynBioDex/libSBOL/issues/153

**Comment by kirichoi** [comment]
Confirmed fixed. 
Weird, because I pulled my repo to HEAD before building it but somehow it didn't work as expected. I had to re-pull the dev branch to get the most recent snapshot.
