### ISSUE TITLE
Integrate round-trip test suite as a git submodule

### ISSUE THREAD

**Issue by bbartley** [SynBioDex/libSBOL#182]
In theory, all SBOL libraries should pull from the same repository of test files.

**Comment by kirichoi** [comment]
Repo for test suite is located [here](https://github.com/SynBioDex/SBOLTestSuite/tree/master/SBOL2).

**Comment by kirichoi** [comment]
What is the current status of failing test files, namely:

partial_pIKE_right_cassette_orig.xml
partial_pIKE_right_casette_orig.xml
partial_pIKE_left_cassette_orig.xml
pIKE_pTAK_toggle_switches_orig.xml
BBa_T9002_orig.xml

I would like the issues resolved first before I change the test file location.

**Comment by cjmyers** [comment]
These files have odd URIs, so I think it is safe to put them in a “skip” category for testing.
