### ISSUE TITLE
Issue with building on Visual Studio

### ISSUE THREAD

**Issue by kirichoi** [SynBioDex/libSBOL#185]
The current develop build errors with 
```
error LNK2005: "public: class sbol::Build & __cdecl sbol::OwnedObject<class sbol::Build>::get(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (?get@?$OwnedObject@VBuild@sbol@@@sbol@@QEAAAEAVBuild@2@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) already defined in libsbolPYTHON_wrap.obj

error LNK2005: "public: class sbol::Design & __cdecl sbol::OwnedObject<class sbol::Design>::get(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (?get@?$OwnedObject@VDesign@sbol@@@sbol@@QEAAAEAVDesign@2@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) already defined in libsbolPYTHON_wrap.obj
```
It seems like there are duplicate definition in .cpp and swig file. The same was true for `sbol::PartShop::pull < ComponentDefinition >` which was resolved by commenting out [this line](https://github.com/SynBioDex/libSBOL/blob/develop/wrapper/libsbol.i#L696). Will it cause any problems?

**Comment by bbartley** [comment]
These are all examples of **specialized** template methods.  It is probably easy to fix.  The specialization needs to be declared in the header files.  So in dbtl.h:
```
    template<>
    Design& OwnedObject<Design>::get(std::string uri);

    template<>
    Build& OwnedObject<Build>::get(std::string uri);
```
There are already some examples of specialized template methods called generate<Test>, generate<Build> etc.

Same goes for the pull methods, except this time the declaration needs to go in partshop.h

I've encountered similar problems when compiling with clang, but for some reason it hasn't complained about these particular examples.  Templates are mysterious sometimes.

**Comment by kirichoi** [comment]
Your suggestion works wonderfully, but I still can not wrap my heads around the issue with `sbol::PartShop::pull < ComponentDefinition >`. The full error is:
```
error LNK2005: "public: void __cdecl sbol::PartShop::pull<class sbol::ComponentDefinition>(class 
std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class sbol::Document 
&,bool)" (??$pull@VComponentDefinition@sbol@@@PartShop@sbol@@QEAAXV?$basic_string@DU?
$char_traits@D@std@@V?$allocator@D@2@@std@@AEAVDocument@1@_N@Z) already defined in 
libsbolPYTHON_wrap.obj
```
Any thoughts?

**Comment by bbartley** [comment]
Is it a similar issue?  So, if you declare the specialized template before the general template in partshop.h.  In theory, the compiler should override the general template definition with the specialized template definition.
```
template<>
void PartShop::pull<ComponentDefinition>(std::string uri, Document& doc, bool recursive); // specialized template declaration

template < class SBOLClass > void PartShop::pull(std::string uri, Document& doc, bool recursive)  // general template declaration
```

**Comment by kirichoi** [comment]
I see. I was confused because I saw the general template and thought it wasn't working for some reason.
