### ISSUE TITLE
Test suite failure

### ISSUE THREAD

**Issue by kirichoi** [SynBioDex/libSBOL#187]
SBOL test suite has been updated and new files have been added. Two of these files fail in round trip tests, namely eukaryotic_promoters.xml (test_case30) and attachment_pointers.xml (test_case28). Full log is available [here](https://travis-ci.org/SynBioDex/libSBOL/builds/337101757?utm_source=email&utm_medium=notification).

test_case28 seems like an issue similar to those '_orig' files. Basically mismatching values causing AssertionError.
```
======================================================================
FAIL: test_case28 (__main__.TestRoundTripSBOL2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "unit_tests.py", line 192, in test_case28
    self.run_round_trip(str(TEST_FILES_SBOL2[28]))
  File "unit_tests.py", line 80, in run_round_trip
    self.assertEqual(self.doc.compare(self.doc2), 1)
AssertionError: 0 != 1
```
```
Values  in http://sys-bio.org/Plan/characterization_protocol/1.0.0::attachment not equal to values in http://sys-bio.org/Plan/characterization_protocol/1.0.0::attachment
Values  in http://sys-bio.org/Plan/characterization_protocol/1.0.0::displayId not equal to values in http://sys-bio.org/Plan/characterization_protocol/1.0.0::displayId
Values  in http://sys-bio.org/Plan/characterization_protocol/1.0.0::persistentIdentity not equal to values in http://sys-bio.org/Plan/characterization_protocol/1.0.0::persistentIdentity
Values  in http://sys-bio.org/Plan/characterization_protocol/1.0.0::version not equal to values in http://sys-bio.org/Plan/characterization_protocol/1.0.0::version
```

test_case30 is caused by libSBOL not being able to read the file.
```
======================================================================
ERROR: test_case30 (__main__.TestRoundTripSBOL2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "unit_tests.py", line 200, in test_case30
    self.run_round_trip(str(TEST_FILES_SBOL2[30]))
  File "unit_tests.py", line 75, in run_round_trip
    self.doc.read(os.path.join(TEST_LOC_SBOL2, split_path[0] + split_path[1]))
  File "/home/travis/install_x64/wrapper/sbol/libsbol.py", line 5906, in read
    return _libsbol.Document_read(self, *args)
RuntimeError: An error occurred while parsing or serializing. The file may not contain valid SBOL
```
```
RDF term resource is forbidden as a property attribute.
RAPTOR_LOG_LEVEL_ERROR
15, -1
http://sbols.org/v2#
```
Are these even valid?

**Comment by cjmyers** [comment]
No, these are different.  You should be passing these.  The “_orig” have strange URIs, so lower priority.

These are files that test the new classes, so any mismatch errors need to be carefully considered.  They could be do to problems, for example, in tags.

To check these, I suggest you compare the original test file to that which is produced via read/write using the library.

**Comment by kirichoi** [comment]
Thanks for clarifying. We will look into this in that case.

**Comment by kirichoi** [comment]
Failure in test_case28 is caused by missing `sbol:Attachment` and something called `myapp:Datasheet`.
Attached is the output of pySBOL when trying to read `attachment_pointers.xml` and write to some file.

[attachment_pointers_test.zip](https://github.com/SynBioDex/libSBOL/files/1692439/attachment_pointers_test.zip)

**Comment by cjmyers** [comment]
myapp:Datasheet is a GenericTopLevel

**Comment by bbartley** [comment]
There were two problems.  One was in the test file.  Object http://sys-bio.org/Plan/characterization_protocol/1.0.0 had duplicate entries in the file, which might be a problem with libSBOLj or SBOLDesigner.  I deleted the duplicate entry and updated the file in the SBOLTestSuite.

The other problem was a bug with libSBOL dropping generic TopLevels which should be corrected now in fabdf36dd44e28634728f50715ed879f831788ae

**Comment by kirichoi** [comment]
Reopening because the test still fails. Good news is, test_case28 is now working. test_case30 still needs to be resolved. Now, test_case22 fails, which involves SBOL1and2Test.xml. I think we had issue with that file before. Is it safe to put it in the expected failures category?

**Comment by cjmyers** [comment]
Yes, SBOL1and2Test.xml is lower priority.  It is a strange example which has SBOL1 code which should be handled as a GenericTopLevel with nested annotations.  However, failure on this test might indicate problems in how you handle nested annotations.

**Comment by bbartley** [comment]
Test case #30 was caused by an artifact in the test file eukaryotic_promoters.xml, probably introduced during some manual editing.  This was causing the raptor parser to throw an exception.  I've corrected the test file and updated the SBOLTestSuite..

**Comment by cjmyers** [comment]
That’s odd. It was generated by sbol designer. Can you provide more detail?

Chris

**Comment by kirichoi** [comment]
Hmm, the test suite is seg faulting at random. Looking into the issue...

**Comment by kirichoi** [comment]
Latest commit by @bbartley fixed the issue. All tests passing.
