### ISSUE TITLE
pySBOL - Reading Document with Custom Nested Object Causes Kernel Death

### ISSUE THREAD

**Issue by nroehner** [SynBioDex/libSBOL#194]
With pySBOL imported in a Python notebook, reading a previously written file that contains a custom nested object causes the kernel to die.

Example Code
----------------

import os

OM_NS = 'http://www.ontology-of-units-of-measure.org/resource/om-2#'

class Measure(Identified, PythonicInterface):
    
    def __init__(self, display_id, name=None, has_numerical_value=None, version='1.0.0'):
        Identified.__init__(self, OM_NS + 'Measure', display_id, version)
        if name is not None:
            self.name = name
        if has_numerical_value is None:
            self.hasNumericalValue = FloatProperty(self.this, OM_NS + 'hasNumericalValue', '0', '1')
        else:
            self.hasNumericalValue = FloatProperty(self.this, OM_NS + 'hasNumericalValue', '0', '1', has_numerical_value)
        self.register_extension_class(Measure, 'om')

import os

Config.setOption('sbol_typed_uris', False)

doc = Document()

comp = doc.componentDefinitions.create('comp')
comp.measures = OwnedPythonObject(comp.this, OM_NS + 'measure', Measure, '0', '*')
ms = comp.measures.create('ms')
ms.hasNumericalValue = FloatProperty(ms.this, OM_NS + 'hasNumericalValue', '0', '1', 100)

doc.write(os.path.join(os.getcwd(), 'example', 'sbol', 'newt.xml'))

boc = Document()
boc.read(os.path.join(os.getcwd(), 'newt.xml'))

**Comment by bbartley** [comment]
This is a subtle point that definitely needs to be documented somewhere.  Every extension object needs a default constructor.  A default constructor is one that can be called without any arguments, eg, Measure() or Mole().  To enable a default constructor, specify a default value for display_id:

def __init__(self, display_id = 'foo', name=None, has_numerical_value=None, version='1.0.0'):
