### ISSUE TITLE
pySBOL - New Roles/Types Cannot Be Appended to a ComponentDefinition

### ISSUE THREAD

**Issue by nroehner** [SynBioDex/libSBOL#195]
Appending roles/types to their respective array properties on a ComponentDefinition does not cause the arrays to change. Consequently, they do not appear in the output serialization.

Example Code
----------------

import os

Config.setOption('sbol_typed_uris', False)

doc = Document()

plasmid = doc.componentDefinitions.create('plasmid')

plasmid.types.append('http://identifiers.org/so/SO:0000988')

plasmid.roles.append('http://identifiers.org/so/SO:0000704')

doc.write(os.path.join(os.getcwd(), 'newt.xml'))

**Comment by bbartley** [comment]
There's no easy or obvious solution to this problem.  It doesn't occur in the libsbol bindings, but is an issue with Python's __getattribute__ method which returns a list object that is not bound to a variable. It is equivalent to [ 'string1' ].append('string2') which returns None.  I haven't figure out a way to fix this yet.

A workaround is to use the following idiom:
plasmid.types = plasmid.types + [ 'http://identifiers.org/so/SO:0000988' ]

**Comment by nroehner** [comment]
Thanks Bryan, this is working for me.

**Comment by bbartley** [comment]
Example documentation demonstrating this idiom has been put on the readthedocs page
