### ISSUE TITLE
Missing measurement.h

### ISSUE THREAD

**Issue by igas** [SynBioDex/libSBOL#215]
Hi,

I'm trying to [update](https://github.com/Homebrew/homebrew-core/pull/41676) `libSBOL` in homebrew and the test fails with:

```
In file included from test.cpp:1:
In file included from /usr/local/Cellar/libsbol/2.3.2/include/sbol/sbol.h:30:
In file included from /usr/local/Cellar/libsbol/2.3.2/include/sbol/document.h:30:
In file included from /usr/local/Cellar/libsbol/2.3.2/include/sbol/componentdefinition.h:30:
/usr/local/Cellar/libsbol/2.3.2/include/sbol/component.h:32:10: fatal error: 'measurement.h' file not found
#include "measurement.h"
         ^~~~~~~~~~~~~~~
```

I'm not a `libSBOL` user nor an expert in `cmake`, just trying to keep homebrew-core up to date.

My best guess will be here: https://github.com/SynBioDex/libSBOL/commit/4507497cd4d23b05eb18c6f7511d0b1242fb8034#diff-6be3438f3924f7603c82c8b35b066575

cmake looks for `measure.h` while source have `measurement.h`.

**Comment by bbartley** [comment]
Fixed in 612faa10
