### ISSUE TITLE
Enable pass through of arbitrary RDF/XML data not in SBOL or extension namespace

### ISSUE THREAD

**Issue by bbartley** [SynBioDex/libSBOL#28]
If an SBOL Document contains elements not in a recognized SBOL or extension namespace, those elements should be passed through serialization

**Comment by hsauro** [comment]
Use iGEM SBOL files for testing

**Comment by bbartley** [comment]
Added methods for handling new namespaces in extension classes in 11e4380.  Added getPropertyValue methods to support extension annotations in 9e3fb4d
