### ISSUE TITLE
Build standalone raptor, libxml2, iconv, zlib dependencies with CMake

### ISSUE THREAD

**Issue by bbartley** [SynBioDex/libSBOL#3]

**Comment by bbartley** [comment]
Currently Windows build of libSBOL depends on precompiled raptor binaries.  Mac OSX build depends on 3rd party package distribution of raptor.  Building raptor from source and integrating with libsbol build would simplify a lot of problems with distributing libSBOL.

**Comment by hsauro** [comment]
Provide librator as a binary.

**Comment by kirichoi** [comment]
I have actually built raptor with some other dependencies on Windows. I don't think this is an issue with other OSs? Anyway, will to rolling out update in CMake to integrate everything.

**Comment by hsauro** [comment]
Delayed for a while.

**Comment by kirichoi** [comment]
Will not be pursued any longer.
