### ISSUE TITLE
Add role and role integration fields

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/libSBOL#45]
Add the role/roleIntegration fields to Component and SequenceAnnotation for SBOL 2.1.

**Comment by cjmyers** [comment]
Add a list of URIs for the Roles in the Component and SequenceAnnotation classes.
Add a URI field for the RoleIntegration into the Component class.

**Comment by kirichoi** [comment]
Fixed by d21ee1883e8d28f4e0c9597ccf42edafd74d374b
