### ISSUE TITLE
Fix instructions for linux installation

### ISSUE THREAD

**Issue by kirichoi** [SynBioDex/libSBOL#47]
Recent update changed cmakelist and the instructions for installations in linux is outdated.

**Comment by kirichoi** [comment]
@bbartley it seems like there has been some changes to gh-pages that are not reflected in master. Can you merge your changes?

**Comment by kirichoi** [comment]
Fixed through 91fd64b41fdf9d1d2ff33888b2d825218503b25c, 893c15a518cc880d02e21160db396c9f4390e548

**Comment by bbartley** [comment]
done.  the manual directory and online docs are back in sync

```
  From: Kiri Choi <notifications@github.com>
```

 To: SynBioDex/libSBOL libSBOL@noreply.github.com 
Cc: bbartley bartleyba@yahoo.com; Mention mention@noreply.github.com
 Sent: Thursday, October 20, 2016 5:16 PM
 Subject: Re: [SynBioDex/libSBOL] Fix instructions for linux installation (#47)

@bbartley it seems like there has been some changes to gh-pages that are not reflected in master. Can you merge your changes?—
