### ISSUE TITLE
Fix issues with building on Linux

### ISSUE THREAD

**Issue by kirichoi** [SynBioDex/libSBOL#48]
Currently there are a lot of problems with CMakeLists that prevents Linux users from building the library. Majority of issues stem from linker paths unspecified for Linux based machine.
There's also problem with building Python binding in Linux since there are no implementation for Linux yet.

**Comment by kirichoi** [comment]
6f9c90b4e7fb4f000ec5e48e935c9990e399aef3 allows users to build on Linux. However, problem with building Python binding is not yet fixed. This issue stems from [wrapper/CMakeList.txt](https://github.com/SynBioDex/libSBOL/blob/master/wrapper/CMakeLists.txt), line 217 from 220 which is only compatible (probably) for Mac OSX.
6f9c90b4e7fb4f000ec5e48e935c9990e399aef3 is tested on Ubuntu 16.04.1 64 bit only. I think I covered 32 bit as well but if someone could test it out it will be great. The only additional package to install is raptor I think (libcurl and libxslt comes with it?) 
To do so, run 

```
sudo apt-get install libraptor2-dev
```

@bbartley : Has Python 3 binding tested?

**Comment by bbartley** [comment]
I've sucssfully built and tested wrappers for python 2.7 and 3.5 but only on Mac OS X so far

**Comment by kirichoi** [comment]
f646dd3d150d79a0d258322a4bb442c82ccf0b7d Fixed issues with building Python 2 bindings on 64 bit Linux, but this is not fully tested yet. Still needs to test 32 bit Linux and Python 3 bindings.
