### ISSUE TITLE
Create a new windows installer with correct header files

### ISSUE THREAD

**Issue by hsauro** [SynBioDex/libSBOL#51]
Create a new windows installer with correct header files.

Note it uses inno setup to create the installer. Somewhere there is a inno setup script. However intallation is quite simple so the scripts could be build from scratch.

**Comment by bbartley** [comment]
Did anyone try the new installer I posted 2 weeks ago?  Did anyone try the detailed instructions for configuring a visual studio project that I put on the documentation?

The old installer might. It have been the problem.  Rather the users may have been linking the dependencies incorrectly.

**Comment by mehersam** [comment]
Can you post a link to where the new installer is?

**Comment by bbartley** [comment]
Hi.  Looks like I was wrong.  I never actually uploaded the new installer until now.  
Get it from here https://github.com/SynBioDex/libSBOL/releases/tag/v2.0.3b-Windows
