### ISSUE TITLE
New page for installation

### ISSUE THREAD

**Issue by kirichoi** [SynBioDex/libSBOL#52]
Update the doxygen page and create a new and separate installation page.

**Comment by kirichoi** [comment]
Commit e65dc4c5f6868a11dc52fa36f808bf902b8c25f5 creates a new page for installation. However, we still need ref to binary installer which is incomplete. Also need instruction for Python bindings post build for Mac OS

**Comment by bbartley** [comment]
Hi, I'd like to move the sections about configuring XCode and VS2013 projects to the Installation page as well, as they seems more logical there.  Currently they are located under Getting Started tab.  Getting Started should be more like a tutorial as in "Getting Started with SBOL".  Any opinions?

**Comment by cjmyers** [comment]
I think the installation page could include the setup of IDE’s, as long as there is a good jumping off point at the top.  Namely, the top should say something like click here to download pre-built libraries for Windows, Mac, etc., click here to get instructions for getting and building from source, click here once you have the libraries to setup a Visual Studio, XCode, Eclipse project.  

We need to make sure there is an easy route for a new user to obtain the library, setup a development environment, and write their first SBOL program.

Chris
