### ISSUE TITLE
Create mac OS installer

### ISSUE THREAD

**Issue by kirichoi** [SynBioDex/libSBOL#58]
Create mac OS installer for libSBOL

**Comment by kirichoi** [comment]
@bbartley : Is there a 32bit version of mac OS installer?

**Comment by bbartley** [comment]
No. I'm currently unable to compile raptor as 32 bit.

```
  From: Kiri Choi <notifications@github.com>
```

 To: SynBioDex/libSBOL libSBOL@noreply.github.com 
Cc: bbartley bartleyba@yahoo.com; Mention mention@noreply.github.com
 Sent: Monday, November 14, 2016 7:14 PM
 Subject: Re: [SynBioDex/libSBOL] Create mac OS installer (#58)

@bbartley : Is there a 32bit version of mac OS installer?—
