### ISSUE TITLE
Building 64bit version of libSBOL in Windows

### ISSUE THREAD

**Issue by kirichoi** [SynBioDex/libSBOL#63]
In source/CMakeList.txt, if OS is Windows, 64bit config is empty. Can you build 64bit libSBOL in Windows? Also there's no catch for static or shared version of the library. 

If not, this is an urgent issue.

**Comment by bbartley** [comment]
Currently it depends on precompiled 32 bit static binaries for raptor.  Don't think there are precompiled dll's available.  Kyle's github repo has a cmake project for raptor which might build from source on windows

**Comment by kirichoi** [comment]
Now you can build static x64 on Windows. Still need to fix shared library issue.
