### ISSUE TITLE
Support VS2015

### ISSUE THREAD

**Issue by kirichoi** [SynBioDex/libSBOL#67]
Currently, building Python bindings returns linker errors apparently because all the dependencies are compiled in VS2013. We need to support VS2015 because at this point majority of the users will try to use it.

Check [https://stackoverflow.com/questions/30412951/unresolved-external-symbol-imp-fprintf-and-imp-iob-func-sdl2](url).

**Comment by bbartley** [comment]
Link statically to raptor, and export a dll

**Comment by kirichoi** [comment]
Fixed this issue by building raptor in VS2015 instead. Still need to fix Cmake and test Python library.

**Comment by kirichoi** [comment]
Python binding seems to work fine so far :)
