### ISSUE TITLE
Need a switch to not include type in URI

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/libSBOL#68]
Should be possible to not include type in URI, if this is not desired.  Also, in libSBOLj, the types are abbreviated (cd,md,seq,mod,col,gtl), should have a way to mimic this for comparison purposes.

BTW: we usually do not include type in the generated URIs as it is a bit of a pain to deal with and keep consistent when copying objects.

**Comment by bbartley** [comment]
Do you have an example URI?

**Comment by cjmyers** [comment]
http://sbols.org/ComponentDefinition/cas9m_BFP_cds/1.0.0
Would like ComponentDefinition to not be included.

**Comment by bbartley** [comment]
#b4d43bd03 adds a flag for turning types on and off in compliant URIs.  Is this sufficient for file comparison between libraries?  I would prefer not to use abbreviated types like cd, md, etc, as this requires some non-extensible, hard-coded type-checking.  Currently, the library automatically infers types for compliant URIs by parsing an object's RDF type, eg http://sbols.org/v2#ComponentDefinition = ComponentDefinition

**Comment by cjmyers** [comment]
How do I set this flag?

**Comment by cjmyers** [comment]
Ok, I figured it out:

```
toggleSBOLCompliantTypes();
```

It is fine to not have the abbreviated types.  I’m tempted to remove this from libSBOLj actually as including types in the URIs is problematic.
