### ISSUE TITLE
File hyperlinks in File tab of Documentation are broken

### ISSUE THREAD

**Issue by bbartley** [SynBioDex/libSBOL#70]

**Comment by kirichoi** [comment]
Where are the files anyway? I cannot find .cpp files anywhere.

**Comment by kirichoi** [comment]
@bbartley It seems like all the example .cpp files are located in your local machine? Could you push it to develop branch?

**Comment by bbartley** [comment]
Done

```
  From: Kiri Choi <notifications@github.com>
```

 To: SynBioDex/libSBOL libSBOL@noreply.github.com 
Cc: bbartley bartleyba@yahoo.com; Mention mention@noreply.github.com
 Sent: Monday, November 21, 2016 6:30 PM
 Subject: Re: [SynBioDex/libSBOL] File hyperlinks in File tab of Documentation are broken (#70)

@bbartley It seems like all the example .cpp files are located in your local machine? Could you push it to develop branch?—
