### ISSUE TITLE
Support building shared library in Windows

### ISSUE THREAD

**Issue by kirichoi** [SynBioDex/libSBOL#73]
Need to add full support for building shared library in Windows

**Comment by hsauro** [comment]
Finish by 21st. Dec

**Comment by kirichoi** [comment]
This is temporarily suspended due to non-trivial issue on SWIG.

**Comment by kirichoi** [comment]
Close to supporting this, fixed most of the linker errors, except this one:

Error	LNK2001	unresolved external symbol "class std::unordered_map<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class sbol::SBOLObject & (__cdecl*)(void),struct std::hash<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,struct std::equal_to<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,class std::allocator<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,class sbol::SBOLObject & (__cdecl*)(void)> > > sbol::SBOL_DATA_MODEL_REGISTER" (?SBOL_DATA_MODEL_REGISTER@sbol@@3V?$unordered_map@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@P6AAAVSBOLObject@sbol@@XZU?$hash@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@U?$equal_to@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$allocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@P6AAAVSBOLObject@sbol@@XZ@std@@@2@@std@@A)	_libsbol	C:\Users\Kiri Choi\projects\libSBOL\_build_2_x86_shared\wrapper\libsbolPYTHON_wrap.obj	1	

Checking what is the problem.

**Comment by kirichoi** [comment]
This is apparently something to do with SWIG. dll works fine as is.

**Comment by kirichoi** [comment]
Commit 7628b7d8c7a1989c28c7ae71383690ad9262cb88 is a temporary fix. Need to solve #133 and #115.
