### ISSUE TITLE
Mac need a brew installer.

### ISSUE THREAD

**Issue by hsauro** [SynBioDex/libSBOL#75]
Mac need a brew installer.

**Comment by bbartley** [comment]
Merged into https://github.com/Homebrew/homebrew-science/commit/05a111cc1317ab1540be0dc3e17d7bfb47e3592b

Still needs testing.  Can interfere with existing installations of libSBOL if the library has been built from source and previously installed.

**Comment by cjmyers** [comment]
I tried this out, and it seems to be working well.
