### ISSUE TITLE
Extra type added to interactions

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/libSBOL#81]
It appears when you create an interaction it adds an extra type:
http://identifiers.org/biomodels.sbo/SBO:0000343

**Comment by cjmyers** [comment]
Problem occurs when you use add on a new Interaction rather than set for types.  With set, it goes away.

**Comment by bbartley** [comment]
http://identifiers.org/biomodels.sbo/SBO:0000343 is the default value for Interaction::type.  The add method by definition will append another type, whereas the set method will overwrite it.

**Comment by cjmyers** [comment]
I see.  I understand that you are trying to make sure all required fields are filled with something, but this one is a bit confusing.  This (and similar filling of required fields) needs to be well documented.  Namely, it should always say in the docs what the default is.  It should also be clear in the tutorial docs too.  The problem with the code docs is that create methods like this one are not documented, only the constructor.

This should be reopened as a documentation issue.

One more thing, shouldn’t the default be 342, molecular or genetic interaction?

**Comment by hsauro** [comment]
Fix in docs and tutorial: By Dec 14.
