### ISSUE TITLE
Go through overleaf document to translate to C++

### ISSUE THREAD

**Issue by hsauro** [SynBioDex/libSBOL#88]
Go through the overleaf tutorial document and create C++ equivalents of the examples. 

Document can be found at:

https://www.overleaf.com/5888197hhnshw#/19453144/

**Comment by hsauro** [comment]
By 7 Dec

**Comment by bbartley** [comment]
Added sections Creating Extension Classes, Creating a TopLevel Annotation, Accessing Annotations Without an Extension.  Still needs a section Sharing and Distributing Extensions

**Comment by hsauro** [comment]
Update copying, setting etc, by 14th, Look for Java and replace.

**Comment by hsauro** [comment]
Check reminder of document for other places to replace Java with C++

**Comment by bbartley** [comment]
Check for copy and paste error in Table 3

**Comment by bbartley** [comment]
Add section for validation

**Comment by kirichoi** [comment]
LibSBOL tutorial works fine, but section 'Other features of libSBOL' is incomplete. It still does not have a section for validation, and there is a section called 'Sharing and Distributing Extensions' without any content.

**Comment by kirichoi** [comment]
Updated with validation information. Please check.
