### ISSUE TITLE
Replace rest bed library with non-GPL equivalent

### ISSUE THREAD

**Issue by hsauro** [SynBioDex/libSBOL#95]
Replace rest bed library with non-GPL equivalent

**Comment by bbartley** [comment]
@kirichoi How difficult would it be to integrate libcurl into Windows build?  Binaries are here https://curl.haxx.se/download.html.  I was successful using it to access SBOLValidator API, and it is distributed under MIT license

**Comment by kirichoi** [comment]
libcurl is already part of Windows static lib as a dependency of raptor2.

**Comment by kirichoi** [comment]
Converted to libCurl.
